### ISSUE TITLE
add word-level alignment

### ISSUE THREAD

**Issue by fangquinlan** [kevinkrahn/grc-sentence-alignment#1]
I have found a relevant model called "[grc-alignment](https://huggingface.co/UGARIT/grc-alignment)"  on HuggingFace, which seems to provide word alignment capabilities for Greek-English language pairs. However, as someone without expertise in this domain, I'm unsure about how to properly utilize and integrate this model into my project.

**Comment by kevinkrahn** [comment]
Word alignment is quite a different process from sentence alignment and outside the scope of the example in this repository. For more information about word alignment you could check out the papers ([here](https://aclanthology.org/2022.lrec-1.634/) and [here](https://aclanthology.org/2022.lt4hala-1.14/)) by the authors of the "grc-alignment" model.
